[paths]
# Base directory for the game servers
server_base_dir = "/mnt/game/server"

# Directory for server settings
servers_file = "/mnt/game/servers.toml"

# Directory for Discord downloads
download_dir = "/var/www/html/discord-downloads"

# Path to the message TOML file
message_toml = "message.toml"

# Path to the log file
log_file = "/var/log/discordbot.log"

# Path to the tmux executable
tmux_executable = "tmux"